print("Program starting.\n\n")
hexnum = input("Insert a hex color: \n")
red = (hexnum[1:3])
green = (hexnum[3:5])
blue = (hexnum[5:7])
print("Colors\n- Red", red, "\n- Green", green, "\n- Blue", blue, "\n\nProgram ending.\n")
